- ros_topic_name: camera_1/color/camera_info
  gz_topic_name: /a201_0000/sensors/camera_1/camera_info
  ros_type_name: sensor_msgs/msg/CameraInfo
  gz_type_name: gz.msgs.CameraInfo
  direction: GZ_TO_ROS
- ros_topic_name: camera_1/points
  gz_topic_name: /a201_0000/sensors/camera_1/points
  ros_type_name: sensor_msgs/msg/PointCloud2
  gz_type_name: gz.msgs.PointCloudPacked
  direction: GZ_TO_ROS
- ros_topic_name: camera_1/depth/camera_info
  gz_topic_name: /a201_0000/sensors/camera_1/camera_info
  ros_type_name: sensor_msgs/msg/CameraInfo
  gz_type_name: gz.msgs.CameraInfo
  direction: GZ_TO_ROS
