a200_0000:
  clearpath_diagnostic_updater:
    ros__parameters:
      serial_number: 'a200-0000'
      platform_model: 'a200'
      ros_distro: 'jazzy'
      latest_apt_firmware_version: 'simulated'
      installed_apt_firmware_version: 'simulated'
      use_sim_time: True
      bms_state_rate: 1.8
      bms_state_tolerance: 0.25
      stop_status_rate: 0.0
      mcu_power_rate: 1.8
      mcu_power_tolerance: 0.25
      estop_rate: 1.8
      estop_tolerance: 0.25
      topics.sensors/lidar3d_0/scan.type: 'sensor_msgs/msg/LaserScan'
      topics.sensors/lidar3d_0/scan.rate: 20.0
      topics.sensors/lidar3d_0/points.type: 'sensor_msgs/msg/PointCloud2'
      topics.sensors/lidar3d_0/points.rate: 20.0
      topics.sensors/imu_0/data.type: 'sensor_msgs/msg/Imu'
      topics.sensors/imu_0/data.rate: 100.0
      topics.sensors/imu_0/mag.type: 'sensor_msgs/msg/MagneticField'
      topics.sensors/imu_0/mag.rate: 0.0
